version: '3.1'
x-database-variables: &database-variable
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql_springboot:3306/anime?createDatabaseIfNotExist=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
services:
  db:
    image: mysql
    container_name: mysql_springboot
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
  springboot2-essentials:
    image: nicholasboari/springboot2-essentials:latest
    ports:
      - 8080:8080
    environment:
      <<: *database-variable
volumes:
  devdojo_data: